defmodule Kore.Codegen.Elixir do
  @moduledoc """
  Main Elixir source code generator for KorE.

  Transforms a verified KorE AST into formatted, idiomatic Elixir source code.
  Handles all expression types, module/function generation, data structs,
  sealed types, and delegates actor generation to `Kore.Codegen.Actor`.

  The public `expr/2` function is also used by `Codegen.Actor` for rendering
  sub-expressions within GenServer handlers.
  """

  alias Kore.AST
  alias Kore.Prelude
  alias Kore.Codegen.{Specs, Actor}

  @spec generate(AST.File.t(), String.t()) :: {:ok, String.t()}
  def generate(%AST.File{} = file, filename) do
    header = "# Generated by KorE v0.1 — do not edit. Source: #{filename}\n\n"
    
    type_index = build_type_index(file.module)
    imports = Enum.map(file.imports || [], &gen_import/1) |> Enum.join("\n")
    module_code = gen_module(file.module, type_index)
    
    code = [header, imports, module_code] |> Enum.reject(&(&1 == "")) |> Enum.join("\n\n")
    {:ok, code}
  end

  def build_type_index(nil), do: %{}
  def build_type_index(%AST.Module{name: mod_name, declarations: decls}) do
    parent_mod = "Kore.#{mod_name}"

    Enum.reduce(decls, %{}, fn
      %AST.DataDecl{name: name, fields: fields}, acc ->
        fields_names = Enum.map(fields, & &1.name)
        full_mod = "#{parent_mod}.#{name}"
        info = %{module: full_mod, fields: fields_names, type: :data}

        acc
        |> Map.put(name, info)
        |> Map.put("#{mod_name}.#{name}", info)
        |> Map.put(full_mod, info)

      %AST.SealedDecl{name: sname, variants: variants}, acc ->
        sealed_mod = "#{parent_mod}.#{sname}"
        variant_names = Enum.map(variants, & &1.name)
        s_info = %{module: sealed_mod, type: :sealed, variants: variant_names}

        acc =
          acc
          |> Map.put(sname, s_info)
          |> Map.put("#{mod_name}.#{sname}", s_info)
          |> Map.put(sealed_mod, s_info)

        Enum.reduce(variants, acc, fn %AST.DataDecl{name: vname, fields: fields}, acc ->
          fields_names = Enum.map(fields, & &1.name)
          v_mod = "#{sealed_mod}.#{vname}"
          v_info = %{module: v_mod, fields: fields_names, type: :variant, sealed: sname}

          acc
          |> Map.put(vname, v_info)
          |> Map.put("#{sname}.#{vname}", v_info)
          |> Map.put("#{mod_name}.#{sname}.#{vname}", v_info)
          |> Map.put(v_mod, v_info)
        end)

      %AST.ActorDecl{name: name}, acc ->
        full_mod = "#{parent_mod}.#{name}"
        info = %{module: full_mod, type: :actor}

        acc
        |> Map.put(name, info)
        |> Map.put("#{mod_name}.#{name}", info)
        |> Map.put(full_mod, info)

      _, acc ->
        acc
    end)
  end

  defp gen_import(%AST.Import{path: path}) do
    if hd(path) == "elixir" do
      "alias #{Enum.join(tl(path), ".")}"
    else
      ""
    end
  end

  defp gen_module(%AST.Module{name: name, declarations: decls}, type_index) do
    module_name = "Kore.#{name}"
    
    funcs_and_vals = Enum.filter(decls, fn d ->
      case d do
        %AST.FunDecl{} -> true
        %AST.ValDecl{} -> true
        _ -> false
      end
    end)
    
    others = Enum.reject(decls, fn d ->
      case d do
        %AST.FunDecl{} -> true
        %AST.ValDecl{} -> true
        _ -> false
      end
    end)
    
    inner = Enum.map(funcs_and_vals, &gen_decl(&1, type_index)) |> Enum.join("\n\n")
    
    other_mods = Enum.map(others, fn
      %AST.DataDecl{} = d -> gen_data(d, module_name, type_index)
      %AST.SealedDecl{} = s -> gen_sealed(s, module_name, type_index)
      %AST.ActorDecl{} = a -> Actor.generate(a, module_name)
    end) |> Enum.join("\n\n")
    
    main_mod = """
    defmodule #{module_name} do
    #{indent(inner)}
    end
    """
    
    [other_mods, main_mod] |> Enum.reject(&(&1 == "")) |> Enum.join("\n\n")
  end

  defp gen_decl(%AST.FunDecl{} = f, type_index) do
    spec = Specs.generate_spec(f, nil, type_index)
    guards = Specs.generate_guards(f, type_index)

    name = Prelude.to_snake_case(f.name)

    params =
      (f.params || [])
      |> Enum.map(fn p ->
        param_name = Prelude.to_snake_case(p.name)

        if p.default do
          "#{param_name} \\\\ #{expr(p.default, type_index)}"
        else
          param_name
        end
      end)
      |> Enum.join(", ")

    head = if guards, do: "def #{name}(#{params}) when #{guards}", else: "def #{name}(#{params})"

    body_exprs =
      if is_map(f.body) and f.body.__struct__ == AST.Block do
        f.body.statements
      else
        [f.body]
      end

    body_str = Enum.map(body_exprs, &expr(&1, type_index)) |> Enum.join("\n")

    body_str =
      if f.return_type == nil or (is_map(f.return_type) and Map.get(f.return_type, :name) == "Unit") do
        body_str <> "\n:ok"
      else
        body_str
      end

    """
    #{spec}
    #{head} do
    #{indent(body_str)}
    end
    """
    |> String.trim_trailing()
  end

  defp gen_decl(%AST.ValDecl{name: name, value: val}, type_index) do
    "#{Prelude.to_snake_case(name)} = #{expr(val, type_index)}"
  end

  defp gen_data(%AST.DataDecl{name: name, fields: fields}, parent_module, type_index) do
    mod_name = if parent_module, do: "#{parent_module}.#{name}", else: "Kore.#{name}"
    
    enforce = fields |> Enum.filter(&(&1.default == nil)) |> Enum.map(&(":" <> Prelude.to_snake_case(&1.name))) |> Enum.join(", ")
    struct_fields = fields |> Enum.map(fn f ->
      k = Prelude.to_snake_case(f.name)
      v = if f.default, do: expr(f.default, type_index), else: "nil"
      "#{k}: #{v}"
    end) |> Enum.join(", ")
    
    typespec_fields = fields |> Enum.map(fn f ->
      "#{Prelude.to_snake_case(f.name)}: #{Specs.type_to_spec(f.type, type_index)}"
    end) |> Enum.join(", ")
    
    new_params = fields |> Enum.map(fn f ->
      p = Prelude.to_snake_case(f.name)
      if f.default do
        "#{p} \\\\ #{expr(f.default, type_index)}"
      else
        p
      end
    end) |> Enum.join(", ")
    
    new_args = fields |> Enum.map(fn f ->
      p = Prelude.to_snake_case(f.name)
      "#{p}: #{p}"
    end) |> Enum.join(", ")

    """
    defmodule #{mod_name} do
      @enforce_keys [#{enforce}]
      defstruct [#{struct_fields}]
      @type t :: %__MODULE__{#{typespec_fields}}
      def new(#{new_params}), do: %__MODULE__{#{new_args}}
    end
    """ |> String.trim_trailing()
  end
  
  defp gen_sealed(%AST.SealedDecl{name: name, variants: variants}, parent_module, type_index) do
    mod_name = if parent_module, do: "#{parent_module}.#{name}", else: "Kore.#{name}"
    
    types = variants |> Enum.map(&("#{mod_name}.#{&1.name}.t()")) |> Enum.join(" | ")
    
    main = """
    defmodule #{mod_name} do
      @type t :: #{types}
    end
    """
    
    vars = variants |> Enum.map(&gen_data(&1, mod_name, type_index)) |> Enum.join("\n\n")
    main <> "\n\n" <> vars
  end

  def expr(node, type_index \\ %{})
  def expr(nil, _), do: ""
  def expr(%AST.ValDecl{name: name, value: val}, type_index), do: "#{Prelude.to_snake_case(name)} = #{expr(val, type_index)}"
  def expr(%AST.Assign{name: name, value: val}, type_index), do: "#{Prelude.to_snake_case(name)} = #{expr(val, type_index)}"
  def expr(%AST.TupleAssign{names: names, value: val}, type_index) do
    "{#{Enum.map(names, &Prelude.to_snake_case/1) |> Enum.join(", ")}} = #{expr(val, type_index)}"
  end
  def expr(%AST.Return{value: nil}, _), do: ""
  def expr(%AST.Return{value: val}, type_index), do: expr(val, type_index)
  def expr(%AST.Block{statements: stmts}, type_index) do
    Enum.map(stmts, &expr(&1, type_index)) |> Enum.join("\n")
  end
  def expr(%AST.If{condition: cond, then_branch: then_b, else_branch: else_b}, type_index) do
    cond_str = expr(cond, type_index)
    then_str = if is_map(then_b) and then_b.__struct__ == AST.Block, do: expr(then_b, type_index), else: expr(then_b, type_index)
    else_str =
      if else_b do
        b_str = if is_map(else_b) and else_b.__struct__ == AST.Block, do: expr(else_b, type_index), else: expr(else_b, type_index)
        "\nelse\n#{indent(b_str)}"
      else
        ""
      end

    "if #{cond_str} do\n#{indent(then_str)}#{else_str}\nend"
  end
  def expr(%AST.When{subject: subj, branches: branches}, type_index) do
    subj_str = expr(subj, type_index)
    branches_str = Enum.map(branches, &gen_when_branch(&1, type_index)) |> Enum.join("\n")
    """
    case #{subj_str} do
    #{indent(branches_str)}
    end
    """ |> String.trim_trailing()
  end
  def expr(%AST.Lambda{params: params, body: body}, type_index) do
    p = if params == nil or params == [], do: "it", else: Enum.map(params, &Prelude.to_snake_case/1) |> Enum.join(", ")
    b = Enum.map(body, &expr(&1, type_index)) |> Enum.join("\n")
    "fn #{p} ->\n#{indent(b)}\nend"
  end
  def expr(%AST.Call{function: func, args: args, trailing_lambda: tl}, type_index) do
    func_name = case func do
      %AST.VarRef{name: n} -> n
      %AST.FieldAccess{receiver: %AST.VarRef{name: m}, field: f} -> "#{m}.#{f}"
      _ -> raise "unsupported func type #{inspect(func)}"
    end
    
    args_strs = Enum.map(args, &expr(&1, type_index))
    args_strs = if tl, do: args_strs ++ [expr(tl, type_index)], else: args_strs
    
    case Prelude.lookup_function(func_name, length(args_strs)) do
      {:ok, {mod, f}} -> 
        if mod == nil, do: "#{f}(#{Enum.join(args_strs, ", ")})", else: "#{mod}.#{f}(#{Enum.join(args_strs, ", ")})"
      {:ok, :read_line} -> "IO.gets(\"\") |> String.trim_trailing()"
      {:ok, :list_literal} -> "[#{Enum.join(args_strs, ", ")}]"
      {:ok, :map_literal} -> "%{#{Enum.join(args_strs, ", ")}}"
      :none -> 
        fn_s = Prelude.to_snake_case(func_name)
        if tl do
          if length(args) > 0 do
            "#{fn_s}(#{Enum.join(Enum.map(args, &expr(&1, type_index)), ", ")}, #{expr(tl, type_index)})"
          else
            "#{fn_s}(#{expr(tl, type_index)})"
          end
        else
          "#{fn_s}(#{Enum.join(args_strs, ", ")})"
        end
    end
  end
  def expr(%AST.MethodCall{receiver: recv, method: meth, args: args, trailing_lambda: tl}, type_index) do
    case recv do
      %AST.VarRef{name: <<char, _::binary>> = mod_name} when char >= ?A and char <= ?Z ->
        args_strs = Enum.map(args, &expr(&1, type_index))
        args_strs = if tl, do: args_strs ++ [expr(tl, type_index)], else: args_strs
        m_snake = Prelude.to_snake_case(meth)
        "#{mod_name}.#{m_snake}(#{Enum.join(args_strs, ", ")})"

      _ ->
        recv_str = expr(recv, type_index)
        args_strs = Enum.map(args, &expr(&1, type_index))
        args_strs = if tl, do: args_strs ++ [expr(tl, type_index)], else: args_strs
        
        case Prelude.lookup_method(meth, length(args_strs)) do
          {:ok, {mod, f, :receiver_first}} ->
            prefix = if is_nil(mod), do: "#{f}", else: "#{mod}.#{f}"
            if length(args_strs) > 0 do
              "#{prefix}(#{recv_str}, #{Enum.join(args_strs, ", ")})"
            else
              "#{prefix}(#{recv_str})"
            end
          {:ok, {mod, f, {:receiver_first, :property}}} ->
            prefix = if is_nil(mod), do: "#{f}", else: "#{mod}.#{f}"
            "#{prefix}(#{recv_str})"
          {:ok, {mod, f, :fold_reorder}} ->
            [init, func] = args_strs
            "#{mod}.#{f}(#{recv_str}, #{init}, #{func})"
          {:ok, {nil, "in", :contains_to_in}} ->
            "#{hd(args_strs)} in #{recv_str}"
          {:ok, {nil, "send", :send_rewrite}} ->
            "send(#{recv_str}, #{hd(args_strs)})"
          {:ok, {nil, "++", :list_append}} ->
            "#{recv_str} ++ [#{hd(args_strs)}]"
          {:ok, {nil, "++", :list_concat}} ->
            "#{recv_str} ++ #{hd(args_strs)}"
          :none ->
            "#{meth}(#{recv_str}#{if length(args_strs)>0, do: ", " <> Enum.join(args_strs, ", ")})"
        end
    end
  end
  def expr(%AST.FieldAccess{receiver: r, field: f}, type_index) do
    case r do
      %AST.NotNull{expr: inner} ->
        inner_str = expr(inner, type_index)
        """
        case (#{inner_str}) do
          nil -> raise "expression was null"
          kore_tmp -> kore_tmp.#{f}
        end
        """ |> String.trim_trailing()

      %AST.SafeAccess{receiver: inner, field: f1} ->
        inner_str = expr(inner, type_index)
        """
        case (#{inner_str}) do
          nil -> nil
          kore_tmp ->
            case kore_tmp.#{f1} do
              nil -> nil
              kore_tmp2 -> kore_tmp2.#{f}
            end
        end
        """ |> String.trim_trailing()

      %AST.Elvis{left: l, right: r_elvis} ->
        l_str = expr(l, type_index)
        r_str = expr(r_elvis, type_index)
        """
        case (#{l_str}) do
          nil -> (#{r_str}).#{f}
          kore_tmp -> kore_tmp.#{f}
        end
        """ |> String.trim_trailing()

      _ ->
        "#{expr(r, type_index)}.#{f}"
    end
  end
  def expr(%AST.SafeAccess{receiver: r, field: f}, type_index) do
    r_str = expr(r, type_index)
    """
    case (#{r_str}) do
      nil -> nil
      kore_tmp -> kore_tmp.#{f}
    end
    """ |> String.trim_trailing()
  end
  def expr(%AST.Elvis{left: l, right: r}, type_index) do
    l_str = expr(l, type_index)
    """
    case (#{l_str}) do
      nil -> #{expr(r, type_index)}
      kore_tmp -> kore_tmp
    end
    """ |> String.trim_trailing()
  end
  def expr(%AST.NotNull{expr: e}, type_index) do
    e_str = expr(e, type_index)
    """
    case (#{e_str}) do
      nil -> raise "expression was null"
      kore_tmp -> kore_tmp
    end
    """ |> String.trim_trailing()
  end

  @op_strings %{
    plus: "+", minus: "-", star: "*", slash: "/", percent: "%",
    eq_eq: "==", not_eq: "!=", less: "<", greater: ">",
    less_eq: "<=", greater_eq: ">=", and_and: "&&", or_or: "||",
    range: ".."
  }
  @unary_op_strings %{not: "!", minus: "-"}

  def expr(%AST.BinOp{op: op, left: l, right: r}, type_index) do
    op_str = Map.get(@op_strings, op, to_string(op))
    "#{expr(l, type_index)} #{op_str} #{expr(r, type_index)}"
  end
  def expr(%AST.UnaryOp{op: op, operand: o}, type_index) do
    op_str = Map.get(@unary_op_strings, op, to_string(op))
    "#{op_str}#{expr(o, type_index)}"
  end
  def expr(%AST.Literal{type: :string, value: v}, _), do: "\"#{v}\""
  def expr(%AST.Literal{type: :null}, _), do: "nil"
  def expr(%AST.Literal{type: :atom, value: v}, _), do: ":#{v}"
  def expr(%AST.Literal{value: v}, _), do: "#{v}"
  def expr(%AST.StringInterp{parts: parts}, type_index) do
    res = Enum.map(parts, fn
      {:string, s} -> s
      {:expr, e} -> "\#{#{expr(e, type_index)}}"
    end) |> Enum.join("")
    "\"#{res}\""
  end
  def expr(%AST.VarRef{name: n}, _) do
    first = String.at(n, 0)
    if first >= "A" and first <= "Z" do
      n
    else
      Prelude.to_snake_case(n)
    end
  end
  def expr(%AST.ConstructorCall{type_name: t, args: args}, type_index) do
    cond do
      t == "Ok" ->
        "{:ok, #{expr(hd(args), type_index)}}"

      t == "Error" ->
        "{:error, #{expr(hd(args), type_index)}}"

      t == "Pair" ->
        "{#{expr(Enum.at(args, 0), type_index)}, #{expr(Enum.at(args, 1), type_index)}}"

      true ->
        mod_prefix =
          case Map.get(type_index, t) do
            %{module: mod} -> mod
            _ -> "Kore.#{t}"
          end

        "#{mod_prefix}.new(#{Enum.map(args, &expr(&1, type_index)) |> Enum.join(", ")})"
    end
  end
  def expr(%AST.CopyCall{receiver: r, updates: u}, type_index) do
    upd = Enum.map(u, fn {k, v} -> "#{Prelude.to_snake_case(k)}: #{expr(v, type_index)}" end) |> Enum.join(", ")
    "%{#{expr(r, type_index)} | #{upd}}"
  end
  def expr(%AST.Spawn{body: b}, type_index) do
    "spawn(fn ->\n#{indent(expr(b, type_index))}\nend)"
  end
  def expr(%AST.Receive{branches: branches}, type_index) do
    b = Enum.map(branches, &gen_when_branch(&1, type_index)) |> Enum.join("\n")
    "receive do\n#{indent(b)}\nend"
  end
  def expr(%AST.For{var: v, iterable: i, body: b}, type_index) do
    "Enum.each(#{expr(i, type_index)}, fn #{Prelude.to_snake_case(v)} ->\n#{indent(expr(b, type_index))}\nend)"
  end
  def expr(%AST.Range{from: f, to: t}, type_index), do: "#{expr(f, type_index)}..#{expr(t, type_index)}"
  def expr(%AST.ListLit{elements: e}, type_index), do: "[#{Enum.map(e, &expr(&1, type_index)) |> Enum.join(", ")}]"
  def expr(%AST.MapLit{entries: e}, type_index) do
    en = Enum.map(e, fn {k, v} -> "#{expr(k, type_index)} => #{expr(v, type_index)}" end) |> Enum.join(", ")
    "%{#{en}}"
  end
  def expr(%AST.PairLit{first: f, second: s}, type_index), do: "{#{expr(f, type_index)}, #{expr(s, type_index)}}"
  def expr(%AST.TupleLit{elements: e}, type_index), do: "{#{Enum.map(e, &expr(&1, type_index)) |> Enum.join(", ")}}"
  def expr(%AST.InOp{element: e, collection: c}, type_index), do: "#{expr(e, type_index)} in #{expr(c, type_index)}"

  defp gen_when_branch(%AST.WhenBranch{pattern: p, body: b}, type_index) do
    pat = gen_pattern(p, type_index)
    body_str = if is_map(b) and b.__struct__ == AST.Block do
      Enum.map(b.statements, &expr(&1, type_index)) |> Enum.join("\n")
    else
      expr(b, type_index)
    end
    "#{pat} ->\n#{indent(body_str)}"
  end
  
  defp gen_pattern(%AST.PatternIs{type_name: t, bindings: b}, type_index) do
    cond do
      t == "Ok" ->
        "{:ok, #{if b && b != [], do: Prelude.to_snake_case(hd(b)), else: "it"}}"

      t == "Error" ->
        "{:error, #{if b && b != [], do: Prelude.to_snake_case(hd(b)), else: "it"}}"

      t in ["String", "Int", "Double", "Boolean", "Atom", "Pid", "List", "Map"] ->
        guard = Specs.type_to_guard(%AST.TypeRef{name: t, nullable: false}, "it", type_index)
        "it when #{guard}"

      t == "Pair" ->
        if b && length(b) == 2 do
          bind0 = Prelude.to_snake_case(Enum.at(b, 0))
          bind1 = Prelude.to_snake_case(Enum.at(b, 1))
          "{#{bind0}, #{bind1}}"
        else
          "it when is_tuple(it)"
        end

      true ->
        case Map.get(type_index, t) do
          %{module: mod, fields: declared_fields} ->
            if b && b != [] do
              binds =
                Enum.zip(declared_fields, b)
                |> Enum.map(fn {field, bind} ->
                  "#{Prelude.to_snake_case(field)}: #{Prelude.to_snake_case(bind)}"
                end)
                |> Enum.join(", ")

              "%#{mod}{#{binds}}"
            else
              "%#{mod}{}"
            end

          %{module: mod} ->
            "%#{mod}{}"

          _ ->
            if b && b != [] do
              binds =
                Enum.map(b, fn bind ->
                  "#{Prelude.to_snake_case(bind)}: #{Prelude.to_snake_case(bind)}"
                end)
                |> Enum.join(", ")

              "%Kore.#{t}{#{binds}}"
            else
              "%Kore.#{t}{}"
            end
        end
    end
  end
  defp gen_pattern(%AST.PatternValue{values: v}, type_index) do
    case length(v) do
      1 -> expr(hd(v), type_index)
      _ -> "x when x in [#{Enum.map(v, &expr(&1, type_index)) |> Enum.join(", ")}]"
    end
  end
  defp gen_pattern(%AST.PatternElse{}, _type_index), do: "_"

  defp indent(str) do
    str |> String.split("\n") |> Enum.map(&("  " <> &1)) |> Enum.join("\n")
  end
end
