defmodule Kore.EndToEndTest do
  use ExUnit.Case, async: true

  describe "full pipeline: source → lexer → parser → codegen" do
    test "hello world module" do
      source = """
      module Main {
          fun main() {
              println("Hello, KorE!")
          }
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "main.kore")
      assert code =~ "defmodule Kore.Main do"
      assert code =~ "IO.puts"
      assert code =~ "Hello, KorE!"
      assert code =~ "# Generated by KorE v0.1"
    end

    test "function with typed params and expression body" do
      source = """
      module Math {
          fun add(a: Int, b: Int): Int = a + b
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "math.kore")
      assert code =~ "defmodule Kore.Math do"
      assert code =~ "def add("
      assert code =~ "@spec"
    end

    test "val and var declarations" do
      source = """
      module Vars {
          fun test() {
              val name = "diego"
              var count = 0
              count = count + 1
              println(name)
          }
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "vars.kore")
      assert code =~ "name = \"diego\""
      assert code =~ "count = 0"
      assert code =~ "count = count + 1"
    end

    test "if/else expression" do
      source = """
      module Logic {
          fun sign(n: Int): String = if (n > 0) "positive" else "non-positive"
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "logic.kore")
      assert code =~ "if"
      assert code =~ "positive"
    end

    test "data record" do
      source = """
      module Models {
          data User(val name: String, val age: Int = 0)
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "models.kore")
      assert code =~ "defmodule Kore.Models.User do"
      assert code =~ "@enforce_keys"
      assert code =~ "defstruct"
      assert code =~ "def new("
    end

    test "string interpolation" do
      source = """
      module Greet {
          fun hello(name: String): String = "Hello, $name!"
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "greet.kore")
      assert code =~ ~s(Hello, \#{)
    end

    test "lambda and method call via prelude" do
      source = """
      module Funcs {
          fun doubled(list: List<Int>): List<Int> = list.map { it * 2 }
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "funcs.kore")
      assert code =~ "Enum.map("
      assert code =~ "fn it ->"
    end

    test "constructor call" do
      source = """
      module Factory {
          data Point(val x: Int, val y: Int)
          fun origin(): Point = Point(0, 0)
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "factory.kore")
      assert code =~ "Kore.Factory.Point.new(0, 0)" || code =~ "Kore.Point.new(0, 0)"
    end

    test "sealed type and when" do
      source = """
      module Shapes {
          sealed Shape {
              data Circle(val r: Double)
              data Rect(val w: Double, val h: Double)
          }

          fun area(s: Shape): Double = when (s) {
              is Circle(val r) -> 3.14 * r * r
              is Rect(val w, val h) -> w * h
          }
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "shapes.kore")
      assert code =~ "defmodule Kore.Shapes.Shape do"
      assert code =~ "defmodule Kore.Shapes.Shape.Circle do"
      assert code =~ "case"
    end

    test "Result Ok/Error" do
      source = """
      module Parser {
          fun parse(s: String): Result<Int, String> =
              if (s == "42") Ok(42) else Error("bad input")
      }
      """

      assert {:ok, code} = Kore.compile(source, file: "parser.kore")
      assert code =~ "{:ok, 42}"
      assert code =~ "{:error, \"bad input\"}"
    end
  end
end
