# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/actor_counter.kore



defmodule Kore.ActorCounter.Counter do
  use GenServer
  
  # -- client API --
  def start(count \\ 0) do
    {:ok, pid} = GenServer.start_link(__MODULE__, %{count: count})
    pid
  end
  
  def increment(pid), do: GenServer.cast(pid, :increment)
  def add(pid, n), do: GenServer.cast(pid, {:add, n})
  def get(pid), do: GenServer.call(pid, :get)

  # -- server callbacks --
  @impl true
  def init(state), do: {:ok, state}
  
  @impl true
  def handle_cast(:increment, state) do
    count = state.count
    count = count + 1
    {:noreply, %{state | count: count}}
  end

  @impl true
  def handle_cast({:add, n}, state) do
    count = state.count
    count = count + n
    {:noreply, %{state | count: count}}
  end

  @impl true
  def handle_call(:get, _from, state) do
    count = state.count
    kore_ret = (fn -> 
    count
    end).()
    {:reply, kore_ret, %{state | count: count}}
  end

end


defmodule Kore.ActorCounter do
  
end
