# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/collections.kore



defmodule Kore.Collections do
  @spec build() :: {[integer()], %{optional(String.t()) => integer()}}
  def build() do
    l = [1, 2, 3]
    m = %{{"a", 1}}
    {l, m}
  end
end
