# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/copy_call.kore



defmodule Kore.CopyCall.User do
  @enforce_keys [:name]
  defstruct [name: nil, age: 0]
  @type t :: %__MODULE__{name: String.t(), age: integer()}
  def new(name, age \\ 0), do: %__MODULE__{name: name, age: age}
end

defmodule Kore.CopyCall do
  @spec update_age(Kore.CopyCall.User.t(), integer()) :: Kore.CopyCall.User.t()
  def update_age(u, new_age) when is_struct(u, Kore.CopyCall.User) and is_integer(new_age) do
    %{u | age: new_age}
  end
end
