# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/data_record.kore



defmodule Kore.DataRecord.User do
  @enforce_keys [:name]
  defstruct [name: nil, age: 0]
  @type t :: %__MODULE__{name: String.t(), age: integer()}
  def new(name, age \\ 0), do: %__MODULE__{name: name, age: age}
end

defmodule Kore.DataRecord do
  
end
