# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/defaults.kore



defmodule Kore.Defaults do
  @spec scale(integer(), integer()) :: integer()
  def scale(x, factor \\ 2) when is_integer(x) and is_integer(factor) do
    x * factor
  end
end
