# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/elvis.kore



defmodule Kore.Elvis.User do
  @enforce_keys [:name]
  defstruct [name: nil]
  @type t :: %__MODULE__{name: String.t()}
  def new(name), do: %__MODULE__{name: name}
end

defmodule Kore.Elvis do
  @spec get_name_or_default(Kore.Elvis.User.t() | nil) :: String.t()
  def get_name_or_default(u) do
    case (case (u) do
      nil -> nil
      kore_tmp -> kore_tmp.name
    end) do
      nil -> "unknown"
      kore_tmp -> kore_tmp
    end
  end
end
