# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/expr_body.kore



defmodule Kore.ExprBody do
  @spec add(integer(), integer()) :: integer()
  def add(a, b) when is_integer(a) and is_integer(b) do
    a + b
  end
end
