# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/for_loop.kore



defmodule Kore.ForLoop do
  @spec iterate([integer()]) :: :ok
  def iterate(list) when is_list(list) do
    Enum.each(list, fn x ->
      IO.puts(x)
    end)
    :ok
  end
end
