# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/import_elixir.kore



alias IO

defmodule Kore.ImportElixir do
  @spec log(String.t()) :: :ok
  def log(msg) when is_binary(msg) do
    IO.puts(msg)
    :ok
  end
end
