# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/lambdas.kore



defmodule Kore.Lambdas do
  @spec process([integer()]) :: integer()
  def process(list) when is_list(list) do
    doubled = Enum.map(list, fn it ->
      it * 2
    end)
    Enum.reduce(doubled, 0, fn acc, x ->
      acc + x
    end)
  end
end
