# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/module_fun.kore



defmodule Kore.ModuleFun do
  @spec greet(String.t()) :: String.t()
  def greet(name) when is_binary(name) do
    "Hello, #{name}"
  end
end
