# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/name_mangling.kore



defmodule Kore.NameMangling do
  @spec fetch_all_data(integer()) :: String.t()
  def fetch_all_data(user_id) when is_integer(user_id) do
    "data_#{user_id}"
  end
end
