# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/not_null.kore



defmodule Kore.NotNull.User do
  @enforce_keys [:name]
  defstruct [name: nil]
  @type t :: %__MODULE__{name: String.t()}
  def new(name), do: %__MODULE__{name: name}
end

defmodule Kore.NotNull do
  @spec get_forced(Kore.NotNull.User.t() | nil) :: String.t()
  def get_forced(u) do
    case (u) do
      nil -> raise "expression was null"
      kore_tmp -> kore_tmp.name
    end
  end
end
