# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/nullability_chain.kore



defmodule Kore.NullabilityChain.User do
  @enforce_keys [:name]
  defstruct [name: nil]
  @type t :: %__MODULE__{name: String.t()}
  def new(name), do: %__MODULE__{name: name}
end

defmodule Kore.NullabilityChain do
  @spec get_name(Kore.NullabilityChain.User.t() | nil) :: String.t() | nil
  def get_name(u) do
    case (u) do
      nil -> nil
      kore_tmp -> kore_tmp.name
    end
  end
end
