# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/sealed_exhaustive.kore



defmodule Kore.SealedExhaustive.Shape do
  @type t :: Kore.SealedExhaustive.Shape.Circle.t() | Kore.SealedExhaustive.Shape.Rect.t()
end


defmodule Kore.SealedExhaustive.Shape.Circle do
  @enforce_keys [:r]
  defstruct [r: nil]
  @type t :: %__MODULE__{r: float()}
  def new(r), do: %__MODULE__{r: r}
end

defmodule Kore.SealedExhaustive.Shape.Rect do
  @enforce_keys [:w, :h]
  defstruct [w: nil, h: nil]
  @type t :: %__MODULE__{w: float(), h: float()}
  def new(w, h), do: %__MODULE__{w: w, h: h}
end

defmodule Kore.SealedExhaustive do
  @spec area(Kore.SealedExhaustive.Shape.t()) :: float()
  def area(s) when is_struct(s, Kore.SealedExhaustive.Shape) do
    case s do
      %Kore.SealedExhaustive.Shape.Circle{r: r} ->
        3.14 * r * r
      %Kore.SealedExhaustive.Shape.Rect{w: w, h: h} ->
        w * h
    end
  end
end
