# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/spawn_receive.kore



defmodule Kore.SpawnReceive do
  @spec worker() :: :ok
  def worker() do
    receive do
      it when is_binary(it) ->
        IO.puts(it)
    end
    :ok
  end
  
  @spec start() :: :ok
  def start() do
    pid = spawn(fn ->
      fn it ->
        worker()
      end
    end)
    send(pid, "hello")
    :ok
  end
end
