# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/string_interp.kore



defmodule Kore.StringInterp do
  @spec format(integer(), integer()) :: String.t()
  def format(a, b) when is_integer(a) and is_integer(b) do
    "sum: #{a + b}"
  end
end
