# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/val_var.kore



defmodule Kore.ValVar do
  @spec test() :: :ok
  def test() do
    name = "diego"
    count = 0
    count = count + 1
    :ok
  end
end
