# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/var_threading_multi.kore



defmodule Kore.VarThreadingMulti do
  @spec check(boolean()) :: integer()
  def check(cond) when is_boolean(cond) do
    x = 1
    y = 10
    {x, y} = if cond do
      x = 2
      y = 20
      {x, y}
    else
      {x, y}
    end
    x + y
  end
end
