# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/var_threading_if.kore



defmodule Kore.VarThreadingIf do
  @spec check(boolean()) :: integer()
  def check(cond) when is_boolean(cond) do
    x = 1
    x = if cond do
      x = 2
      x
    else
      x
    end
    x
  end
end
