# Generated by KorE v0.1 — do not edit. Source: /home/goldoni/WorkSpace/KorE/test/golden/cases/when_values.kore



defmodule Kore.WhenValues do
  @spec describe(integer()) :: String.t()
  def describe(n) when is_integer(n) do
    case n do
      0 ->
        "zero"
      x when x in [1, 2] ->
        "small"
      it ->
        "big"
    end
  end
end
